apiVersion: v1
kind: Service
metadata:
  name: ml-signal-service
  namespace: {{ .Values.global.appNamespace | default "mariaalpha" }}
  labels:
    {{- include "ml-signal-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.appPort }}
      targetPort: app
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      appProtocol: grpc
      protocol: TCP
  selector:
    {{- include "ml-signal-service.selectorLabels" . | nindent 4 }}
