apiVersion: v1
kind: Service
metadata:
  name: market-data-gateway
  namespace: {{ .Values.global.appNamespace | default "mariaalpha" }}
  labels:
    {{- include "market-data-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.appPort }}
      targetPort: app
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "market-data-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-gateway-grpc
  namespace: {{ .Values.global.appNamespace | default "mariaalpha" }}
  labels:
    {{- include "market-data-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      appProtocol: grpc
      protocol: TCP
  selector:
    {{- include "market-data-gateway.selectorLabels" . | nindent 4 }}
