{{- if .Values.serviceMonitor.enabled }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: market-data-gateway
  namespace: {{ .Values.global.appNamespace | default "mariaalpha" }}
  labels:
    {{- include "market-data-gateway.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames: ["{{ .Values.global.appNamespace | default "mariaalpha" }}"]
  selector:
    matchLabels:
      {{- include "market-data-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
