spring:
  application:
    name: post-trade
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:mariaalpha}
    username: ${POSTGRES_USER:mariaalpha}
    password: ${POSTGRES_PASSWORD:mariaalpha}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
