spring:
  application:
    name: market-data-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:mariaalpha}
    username: ${POSTGRES_USER:mariaalpha}
    password: ${POSTGRES_PASSWORD:mariaalpha}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
